apiVersion: v1
kind: Service
metadata:
  name: client-app-service-svc
  namespace: microservice
spec:
  selector:
    app: client-app-service
  ports:
  - protocol: TCP
    port: 3000
    targetPort: 3000
  type: ClusterIP
